#%RAML 1.0
title: Contrevenants inspection alimentaire API
mediaType: application/json
baseUri: http://127.0.0.1:5000
version: 1

types:
  Contravention:
    type: object
    properties:
      id_poursuite: number
      id_business: number
      date: string
      description: string
      adresse: string
      date_jugement: string
      etablissement: string
      montant: number
      proprietaire: string
      ville: string
      statut: string
      date_statut: string
      categorie: string
    additionalProperties: false
    example: |
      {
        "id_poursuite": 100,
        "id_business": 200,
        "date": "2022-11-05",
        "description": "Personnes affectées à la consommation de produits",
        "adresse": "123 avenue Chemin, Montréal, Québec",
        "date_jugement": "2022-12-05",
        "etablissement": "Nom Établissment",
        "montant": 100,
        "proprietaire": "Nom Proprietaire",
        "ville": "Montréal",
        "statut": "Ouvert",
        "date_statut": "2024-01-02",
        "categorie": "Restaurant"
      }
  DateRange:
    type: object
    properties:
      du: string
      au: string

/api:
  /contrevenants:
    get:
      description: Récupère des données en fonction d'une plage de dates spécifiée.
      queryParameters:
        du:
          type: string
          description: Date de début au format YYYY-MM-DD.
          example: "2022-05-08"
          required: true
        au:
          type: string
          description: Date de fin au format YYYY-MM-DD.
          example: "2024-05-15"
          required: true
      responses:
        200:
          body:
            application/json:
              type: Contravention[]
            example: |
              [
                {
                  "id_poursuite": 100,
                  "id_business": 200,
                  "date": "2022-11-05",
                  "description": "Personnes affectées à la consommation de produits",
                  "adresse": "123 avenue Chemin, Montréal, Québec",
                  "date_jugement": "2022-12-05",
                  "etablissement": "Nom Établissment",
                  "montant": 100,
                  "proprietaire": "Nom Proprietaire",
                  "ville": "Montréal",
                  "statut": "Ouvert",
                  "date_statut": "2024-01-02",
                  "categorie": "Restaurant",
                  {
                  "id_poursuite": 300,
                  "id_business": 350,
                  "date": "2020-11-05",
                  "description": "Personnes affectées à la consommation de produits",
                  "adresse": "123 avenue Chemin, Montréal, Québec",
                  "date_jugement": "2020-12-05",
                  "etablissement": "Nom Établissment",
                  "montant": 500,
                  "proprietaire": "Nom Proprietaire",
                  "ville": "Montréal",
                  "statut": "Ouvert",
                  "date_statut": "2024-01-02",
                  "categorie": "Restaurant",
                  }

                }
              ]

/api:
  /etablissements:
    get:
      description: Récupère la liste des établissements et on indique le nombre
       d'infractions connues. La liste est triée en ordre décroissant du nombre d'infractions:
      responses:
        200:
          body:
            application/json:
              type: EtablissementsListe
            example: |
              [
                {
                  "id_poursuite": 100,
                  "id_business": 200,
                  "date": "2022-11-05",
                  "description": "Personnes affectées à la consommation de produits",
                  "adresse": "123 avenue Chemin, Montréal, Québec",
                  "date_jugement": "2022-12-05",
                  "etablissement": "Nom Établissment",
                  "montant": 100,
                  "proprietaire": "Nom Proprietaire",
                  "ville": "Montréal",
                  "statut": "Ouvert",
                  "date_statut": "2024-01-02",
                  "categorie": "Restaurant",
                  {
                  "id_poursuite": 300,
                  "id_business": 350,
                  "date": "2020-11-05",
                  "description": "Personnes affectées à la consommation de produits",
                  "adresse": "123 avenue Chemin, Montréal, Québec",
                  "date_jugement": "2020-12-05",
                  "etablissement": "Nom Établissment",
                  "montant": 500,
                  "proprietaire": "Nom Proprietaire",
                  "ville": "Montréal",
                  "statut": "Ouvert",
                  "date_statut": "2024-01-02",
                  "categorie": "Restaurant",
                  }

                }
              ]
